show blockchain log entries on errors
mlabs-haskell/plutus-simple-model pull request #13
Opened 2022-04-26 16:32 UTC by euonymos

2022-04-26 18:06 UTC, euonymos commented
Looks like CI runs into OOM or something.

2022-05-10 10:42 UTC, anton-k requested changes

2022-05-10 10:42 UTC, anton-k commented on src/Plutus/Test/Model/Blockchain.hs
> +    stateDump :: Blockchain -> String
No need for this function. It seems to be doing something that user can do

2022-05-10 10:42 UTC, anton-k commented on src/Plutus/Test/Model/Blockchain.hs
> +      logInfo $ stateDump s s
User can do it if user needs that. No need to have forced log

2022-05-10 10:42 UTC, anton-k commented on src/Plutus/Test/Model/Fork/TxExtra.hs
> +  , extra'descr          :: Last String
Let's keep `Tx` for things that relate to Cardano. This is test concept to improve readability. We can use `BchNames` for that or add this info to something that is not related to `Tx`. For example to Stats. But `BchNames` is preferable. It's the place to keep human readably synonyms for pretty printing.

2022-05-12 11:30 UTC, anton-k commented
Thanks for your improvements to the lib so far. I will accept the PR if it pass CI. 
Fixing the lint job is ok. It seems that build fails by out of resources exception on CI-node

2022-05-12 11:42 UTC, anton-k commented
Also thanks for docs update it's very helpful to keep it up to date.

2022-05-12 22:40 UTC, euonymos commented
@anton-k I fixed lint tips, and reworked the prettifier, now it looks far better.
![image](https://user-images.githubusercontent.com/103441514/168179090-91db6fc1-4aac-462f-a420-3dc81e85121c.png)

2022-05-13 11:11 UTC, anton-k commented
Looks great!

2022-05-13 11:11 UTC, merged

2022-05-13 11:12 UTC, anton-k commented
Maybe it would be cool to have option to show short versions of hashes, like github does for commits