bring over evalScript start utxoForTransaction
mlabs-haskell/plutus-simple-model pull request #96
Opened 2023-02-07 18:23 UTC by Geometer1729

Closes #91

2023-02-08 20:18 UTC, Geometer1729 commented on psm/src/Plutus/Model/Mock.hs
> +  runValidate $ do
Just caught this while reading the module and it bugged me so I pulled the `>>= \tx ->` into the do block

2023-02-13 16:13 UTC, AriFordsham requested changes
Overall very nice! Nice to see `ModelMock` getting tidier!

2023-02-13 16:13 UTC, AriFordsham commented on cardano-simple/src/Cardano/Simple/Cardano/Babbage.hs
> +  toCardanoTx n p e tx = toBabbageTx (Plutus.txScripts tx) n p e tx
Can we push this down into `toBabbageTx`?

2023-02-13 16:13 UTC, AriFordsham commented on cardano-simple/src/Cardano/Simple/Eval.hs
> +      (Alonzo.transProtocolVersion $ getField @"_protocolVersion" pparams)
Can we replace uses of `getField` with overloaded record dot syntax?
```suggestion
      (Alonzo.transProtocolVersion pparams._protocolVersion)
```

2023-02-13 16:13 UTC, AriFordsham commented on psm/src/Plutus/Model/Mock.hs
> +        Right bal -> pure bal
```suggestion
        case txBalance @era utxos params network tx extra of
          Left err -> throwError $ FailToCardano err
          Right bal -> when
            (bal /= mempty)
            (throwError $ NotBalancedTx $ fromCardanoValue bal)
```

2023-02-13 16:18 UTC, Geometer1729 commented on cardano-simple/src/Cardano/Simple/Cardano/Class.hs
> -    Map P.ScriptHash (C.Versioned P.Script) ->
Oh sorry for jumping the gun on that. I though I remembered you saying yes must've been a different thread and Id didn't look closely or something.

2023-02-13 16:30 UTC, Geometer1729 commented
> Overall very nice! Nice to see `ModelMock` getting tidier!
> 
> I'm assuming you're confident no functional changes have resulted. Have you run the test suite to see if it catches anything?

Thanks :) . I'm reasonably confident I haven't changed the behavior, and yes the test suite still passes.

2023-02-13 16:45 UTC, AriFordsham approved these changes

2023-02-13 16:47 UTC, merged